### ISSUE TITLE
Missed notifications improvements

### ISSUE THREAD

**Issue by atymic** [thomasjohnkane/snooze#10]
I think it'd be a good idea to have an event or notification in the case that we have a large backlog of unsent notifications (snooze was not running for x days).

Otherwise it could just go unnoticed by the developer unless they checked the table.

Also, adding a command to cancel one that were missed (or doing this when the above notification is sent?)

**Comment by thomasjohnkane** [comment]
Wouldn't this just have to be a separate cron that checks for unsent notifications in the table or if the first cron is running? Seems like they could both fail. I think I used a separate service called Cronhub to monitor cron activity like this before.

How do you envision sending this event/notification?

**Comment by atymic** [comment]
I more mean doing something when the command runs again for the first time. 
For example, seeing that the backlog has 100 notifications, cancel them & log (or exception) to make sure the dev is aware?

**Comment by thomasjohnkane** [comment]
The tolerance field already helps prevent the deluge of old notifications right? Are you meaning to send an event if there is something that should be sent but is older than the tolerance allows?

**Comment by atymic** [comment]
I think we can close this for now, and consider re-visiting later if we come across the issue in prod.
