### ISSUE TITLE
Feature Request: Use Prunable trait

### ISSUE THREAD

**Issue by jansgescheit** [thomasjohnkane/snooze#105]
Since Laravel 8 the Trait [Prunable](https://laravel.com/api/8.x/Illuminate/Database/Eloquent/Prunable.html) exist ([Doc](https://laravel.com/docs/9.x/eloquent#pruning-models)), it would be nice to have it in upcoming releases as annother option to `snooze:prune`.

**Comment by atymic** [comment]
I don't think this needs to be used with the default, but feel free to PR any enhncements to the snooze command.
