### ISSUE TITLE
Possible Bug: Multiple Notifications sent via concurrent snooze:send command

### ISSUE THREAD

**Issue by simonmaass** [thomasjohnkane/snooze#118]
When you have a very large number of schedules notifications to be sent, then the "snooze:send" command can run for multiple minutes (in our case 5 minutes) and if the sendFrequency is set to 1 minute (this is the default) then for the same notificatios multiple notifications will be excuted as the "sent_at" timestamp is not yet set in the database for the next "snooze:send" command....

Possible solution:
In my opinion the "snooze:send" command should never run concurrently! I dont see a use case where this would be valid...

Therefore: withoutOverlapping should be added in https://github.com/thomasjohnkane/snooze/blob/master/src/ServiceProvider.php

**Comment by andreliem** [comment]
+1. We had the exact same issue as well this week. The amount of notifications to send was greater than the frequency duration set so users received multiple notifications.
