### ISSUE TITLE
Accessing send_at attribute

### ISSUE THREAD

**Issue by erekle13** [thomasjohnkane/snooze#120]
How can I access the send_at attribute?

When I try to access it on the result of ScheduledNotification::findByMeta() I get:
Undefined property: Thomasjohnkane\Snooze\ScheduledNotification::$send_at

If I use getSendAt() on model, I get following:
Thomasjohnkane\Snooze\ScheduledNotification::getSendAt(): Return value must be of type Carbon\CarbonInterface, string returned

What am I missing?

**Comment by atymic** [comment]
This is due to a cast issue, fixed in #122
