### ISSUE TITLE
Scheduled notification events

### ISSUE THREAD

**Issue by atymic** [thomasjohnkane/snooze#14]
I think we should add an event dispatched before and after a notification is sent.

It would allow the application to do some checks before the notification is sent (ie, ensure that the user is still active, etc) and after (record that x email was sent)

**Comment by thomasjohnkane** [comment]
Could we handle this with just having a method on the notification class like `shouldStillSend()` to check to see if sending is still required? You can already log that a notification was sent in the `toArray()` method of the notification class.

I'm going to create a PR for the should still send check, and we can discuss events down the road if there's a more concrete example.

**Comment by atymic** [comment]
I was actually thinking of doing it that way, but didn't have a chance to get it implemented yet :)

Thanks for doing the PR, will check it out now :)

I think it's probably still worth firing an event on sent (at least)

**Comment by LeonAlvarez** [comment]
Is this implemented?

**Comment by atymic** [comment]
@LeonAlvarez 

Yep:
https://github.com/thomasjohnkane/snooze/blob/master/src/Models/ScheduledNotification.php#L77
