### ISSUE TITLE
Admin UI &/Or Nova Package

### ISSUE THREAD

**Issue by atymic** [thomasjohnkane/snooze#22]
Just moving this from the readme so we can discuss 😄 

- [ ] Show tab for past notifications
- [ ] Show tab for scheduled notifications
- [ ] Give CRUD options for scheduled notifications
- [ ] Create as a Nova Package

**Comment by laxsmi** [comment]
Hi,

I have developed a basic admin UI for the Snooze package. It allows to create drip notifications based on events emitted from the host app. The features are currently very limited, but it works and it could be a good basis to build up additional features.

Would you be considering a PR for this? Do you have any guidelines I should follow to integrate it well with the rest of the package?

**Comment by atymic** [comment]
@laxsmi feel free to make a PR :)
Either we can merge it into this report, or we can at least have a section in the readme with install instructions (would probably work better for those who don't want a UI)

**Comment by atymic** [comment]
@thdebay do you still use snooze?
