### ISSUE TITLE
Tag v1.0

### ISSUE THREAD

**Issue by atymic** [thomasjohnkane/snooze#24]
I think we are ready to tag the first version of the package.
Is there anything else we need to do before then?

cc @thomasjohnkane

**Comment by thomasjohnkane** [comment]
I agree - you're already using it successfully in a project right?

**Comment by thomasjohnkane** [comment]
Added a draft - take a look.

**Comment by atymic** [comment]
Looks good to me!

I'm currently on dev-master and working fine in production.

**Comment by atymic** [comment]
We are stable 🎉
