### ISSUE TITLE
You don't pass the $notifiable to the shouldInterrupt() method ?

### ISSUE THREAD

**Issue by empresarrollo** [thomasjohnkane/snooze#30]
If I understand the docs, I should be able to add a `public function shouldInterrupt($notifiable)` to my `class MyCoolNotification extends Notification`, something like:

```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;

class MyCoolNotification extends Notification 
{
    use Queueable;

    public function shouldInterrupt($notifiable) {
        return $notifiable->my_bool_value;
    }
}
```

but I get an exception: ` Too few arguments to function App\Notifications\MyCoolNotification::shouldInterrupt(), 0 passed in ..............\vendor\thomasjohnkane\snooze\src\Models\ScheduledNotification.php on line 95 and exactly 1 expected`

in that line 95 you call: `return (bool) $notification->shouldInterrupt();`

**I think you are missing passing the $notifiable** ??

**Comment by atymic** [comment]
Good catch!

You're right, it's currently not passing the `$notifiable` object.

I'll PR a fix shortly, thanks for the report!
