### ISSUE TITLE
Publish migrations

### ISSUE THREAD

**Issue by mpociot** [thomasjohnkane/snooze#36]
Great job on the package!
I would like to add some additional fields on the migration - therefore it would be great if the migration wouldn't get loaded automatically from the service provider, but if I could just publish and modify it instead.
Would you accept a PR with that change?

**Comment by atymic** [comment]
Thanks Marcel!

Would be happy to accept a PR with that change.
May I ask what you'd be changing in the migration? The way the package is structured it doesn't really provide direct access to the model.

**Comment by ettiennelouw** [comment]
On this i would also like to publish the migrations, we are using multitenancy and without the migration, it creates the tables in the main database and not the tenants database, so as a hack we have to add an entry into the migrations table on the main database and manually create the table, well duplicate the table manually on each tenant.

**Comment by atymic** [comment]
Feel free to PR a solution for this
