### ISSUE TITLE
$notifiable->getMorphClass() instead of get_class($notifiable)?

### ISSUE THREAD

**Issue by ziming** [thomasjohnkane/snooze#40]
This way when Relation::morphMap is used

The entry in the database table is users instead of App\User

See: 

https://laravel.com/docs/6.x/eloquent-relationships#custom-polymorphic-types

https://josephsilber.com/posts/2018/07/02/eloquent-polymorphic-relations-morph-map

**Comment by atymic** [comment]
Sorry, forgive me but what advantage does this provide?

**Comment by ziming** [comment]
So things won't break if you move model classes to another namespace.

If relation morph map is not defined for a model, it returns the get_class() string, but if it is defined, $user->getMorphClass() returns the defined name, which is usually the table name by convention.

```php
// In AppServiceProvider
Relation::morphMap([
    'users' => User::class,
]);
```

Which can happen if you scheduled a notification to be sent 1 month later, in between did some refactoring and the model class is in another namespace now.

**Comment by atymic** [comment]
I had a look into this and unfortunately I don't think this will fix the issue if you move the class, as the serialized `target` still contains the actual classname:

```
O:45:"Illuminate\Contracts\Database\ModelIdentifier":4:{s:5:"class";s:39:"Thomasjohnkane\Snooze\Tests\Models\User";s:2:"id";i:1;s:9:"relations";a:0:{}s:10:"connection";s:6:"sqlite";}
```  

Here's the relevant part of the laravel serialization code:
https://github.com/laravel/framework/blob/75827f9982feb3befb0489d879cf41718b43c391/src/Illuminate/Database/Eloquent/Collection.php#L520-L535
