### ISSUE TITLE
Question:how you check the notification entries in table is due?

### ISSUE THREAD

**Issue by metallurgical** [thomasjohnkane/snooze#41]
Very great package i would say!

This is not really an issue, but rather a question of my curiosity. May i know, how you check the notification entries in table is due, let say when after running `snooze:send` command?

Appreciate for the clarification!

Thanks

**Comment by atymic** [comment]
https://github.com/thomasjohnkane/snooze/blob/master/src/Console/Commands/SendScheduledNotifications.php#L34-L38

:)

**Comment by metallurgical** [comment]
i see, i saw this statement actually, but not able to figure it out how its actually works.. After reading it back, now its become more clear,, i took the hardest way by using this package `dragonmantank/cron-expression`,,

Anyway, thanks.

**Comment by atymic** [comment]
Laravel actually has built in cron support :)
https://laravel.com/docs/6.x/scheduling

**Comment by metallurgical** [comment]
yup, knew it.. But not find a way to make it flexible when it comes to self-defined schedule(users able to set their own date & time)  by users.
