### ISSUE TITLE
Unable to retrieve parameters in notification

### ISSUE THREAD

**Issue by laxsmi** [thomasjohnkane/snooze#48]
Hello,

I am a little confused by the following behaviour.

```
// this is working
Notification::send(
    $event->user, // Target
    new DripMarketingNotification($rule)
);

// this is not
ScheduledNotification::create(
    $event->user, // Target
    new DripMarketingNotification($rule),
    Carbon::now()->addSeconds($rule->delay) // Send At
);
```

The scheduled notification appears in the DB table, but when I run `artisan schedule:run` I get the following error in the logs:

`Undefined property: $dripRule {"exception":"[object] (ErrorException(code: 0) at .../src/Notifications/DripMarketingNotification.php:43)`

But the regular Notification facade works perfectly. Is there something I am missing?

This is the code from `DripMarketingNotification.php`

```
public function toMail($notifiable)
{
    return (new DripMarketingMail($notifiable, $this->dripRule))->to($notifiable->email);
}
```

**Comment by laxsmi** [comment]
After more debugging, I found out the issue, it wasn't related to your package. Sorry about the trouble...

Thanks for all your work on this great package!

**Comment by atymic** [comment]
No worries, glad you got it solved :)
