### ISSUE TITLE
Reference to $notification for canceling/reschedule

### ISSUE THREAD

**Issue by eAvio** [thomasjohnkane/snooze#49]
**I'm having this scenario:**
1. User needs to set targetDay
2. In model I'm listening for "created" event
3. $user->notifyAt(new TargetDayReminder, $targetDay); 
Along with that I'm scheduling some more events for the same entry/user - for example BirthdayReminder ...

This works.

But I'm having problem when user change $targetDay.
I'm listening to models "updated" event and I know there is "reschedule" method available in ScheduledNotifications.

But to call "reschedule", I need to have reference to $notification.
**From your example: $notification->reschedule($rescheduleAt)**

What would be the best way to get that reference? 

I guess I should be able to get reference from this 3 parameters:
- Class name of notifiable class "TargetDayReminder"
- User
- SendAt

Or should I use completely different approach to handle situations like this?

**Comment by eAvio** [comment]
Another way of getting notification reference could be by defining some additional parameters - for example I could use $user->notifyAt(new TargetDayReminder($someParameter), $targetDay);

Based on $someParameter we could easily find specific notification. 

For example something like this:
$notification = findByNotificationParameter(TargetDayReminder, $someParameter);

**Comment by atymic** [comment]
So, you can:
- Find all the notifications for a user and then reshedule the one your want 
https://github.com/thomasjohnkane/snooze/blob/master/src/ScheduledNotification.php#L85
- Save the ID of the created notification somewhere, and grab it directly by it's id: https://github.com/thomasjohnkane/snooze/blob/master/src/ScheduledNotification.php#L85

For example, i'm using this to reschedule reminders:

```
/** @var ScheduledNotification $bookingReminder */
        $bookingReminder = ScheduledNotification::findByTarget($booking)->first();

        if (!$bookingReminder  || $bookingReminder->isSent()) {
            return;
        }

        $newReminderDate = $booking->starts_at->subDays(3);

        if ($newReminderDate !== $bookingReminder->getSendAt()) {
            $bookingReminder->reschedule($newReminderDate);
        }

```

**Comment by eAvio** [comment]
Thank you for the answer @atymic . 
This could work!

Although it took me quite a lot of time to figure it out how to use `->notify_at` on a model other than `App\User`. 

For other readers would be helpful to mention, that if you are using SnoozeNotifiable on models other than App\User that model should be "notifiable".

That means method routeNotificationFor needs to be defined on your model (on App\User that method is added by default):

```
public function routeNotificationFor($driver)
{  
        switch ($driver) {
            case 'database':
                return $this->notifications();
            case 'mail':
                return $this->user->email;
            case 'nexmo':
                return $this->user->phone_number;
        }
}
```

Here is good read about how channels work:
[https://divinglaravel.com/how-notification-channels-work-in-laravel](https://divinglaravel.com/how-notification-channels-work-in-laravel)

Read section "Customizing The Recipient"
[https://laravel.com/docs/7.x/notifications#customizing-the-recipient](https://laravel.com/docs/7.x/notifications#customizing-the-recipient)


@atymic Another issue I discovered is how to pass parameters to Nofitication. 
After serialization/deseralization they are lost.
For example "$someParameter" is not preserved after deserialization.

`$user->notifyAt(new TargetDayReminder($someParameter), $targetDay);`

Is this expected behaviour?

**Comment by atymic** [comment]
>@atymic Another issue I discovered is how to pass parameters to Nofitication.
After serialization/deseralization they are lost.
For example "$someParameter" is not preserved after deserialization.

As long as you set a property on the object, it should be preserved?
