### ISSUE TITLE
How get ID after sending scheduled notification

### ISSUE THREAD

**Issue by mehdirochdi** [thomasjohnkane/snooze#51]
how i can get **id** after send notification `$user->notifyAt(some_notification_class)`
i want stored in my table to cancel specific notification for user.
for cancel notification i use 
``$scheduledNotification= ScheduledNotification::find(scheduled_notification_id);
$scheduledNotification->cancel();``

**Comment by atymic** [comment]
You can call the `getId` function on the returned object :)

```php
$notif = $user->notifyAt(some_notification_class);

$notif->getId(); // 4554
```
