### ISSUE TITLE
Is there any way to schedule notifications for them to happen daily?

### ISSUE THREAD

**Issue by danslabs** [thomasjohnkane/snooze#53]
I'm trying to make for my backend to send a notification each day that that comes closer to an indicated date.

For example, if my user adds the date "16-07-2020", he should be getting a notification "your deadline is in 1 day!" (as today is 15).

How is it possible to make it with this package?

**Comment by atymic** [comment]
To be honest, I think this is probably a better job for a scheduled task. I'd create one that runs daily and loops over the models that are ready for notifications.

This package isn't well suited for that, as you'd have to pre-emptively generate notifications in a loop (and it would get messy if the users changed the due date).

**Comment by danslabs** [comment]
Thank you for the answer, made a command, and inside of it I looped its job, thank you for letting me know!
