### ISSUE TITLE
Custom Data

### ISSUE THREAD

**Issue by lioneaglesolutions** [thomasjohnkane/snooze#68]
Is there a way to add custom data to a notification? For example, writing an email or SMS and then scheduling that notification ? I can see there is a link in the documentation for support custom data, however it no longer exists, and the custom code example files are no longer in the documentation. Currently, when trying to do this, the notification just doesn't send.

**Comment by StubyProjects** [comment]
Yes, had the same bug and just forgot to add public variables of the custom data to the notification class. If you follow the design of the model they are using in the test folder it should work: [TestNotification](https://github.com/thomasjohnkane/snooze/blob/master/tests/Notifications/TestNotification.php)
