### ISSUE TITLE
How can I cancel the notification

### ISSUE THREAD

**Issue by Ihabafia** [thomasjohnkane/snooze#72]
Hi, I did create a notification from a model:
```php
$finance->notifyAt(new ThreeConsecutiveNsfsDayOneEmail(), $this->due);
```

Now, I need to cancel this notification, the documentation is saying ```$notification->cancel();``` but how can I have the notification.  I tried the following but didn't work.
```php
$notification = new ThreeConsecutiveNsfsDayOneEmail();
$notification->cancel();
```

So, what is the solution to do so, can you update the documentation.

Thank you,

**Comment by atymic** [comment]
You can either use `findByTarget` [here](https://github.com/thomasjohnkane/snooze/blob/master/src/ScheduledNotification.php#L86) or `find` [here](https://github.com/thomasjohnkane/snooze/blob/master/src/ScheduledNotification.php#L66) to load the scheduled notification, then you can cancel the one you want using the `cancel` method.
