### ISSUE TITLE
"App\Models\User is not notifiable" error

### ISSUE THREAD

**Issue by lorenzosfarra** [thomasjohnkane/snooze#76]
Hi,

thanks a lot for your amazing work.

I would like to understand the given error. According to the documentation in the README file, I should have a Model like this:

```
class User extends Model {
    use SnoozeNotifiable;

    // ...
}
```

that sadly fires the error in the issue subject.

If look closer, the error is thrown in lines 46-48 of ScheduledNotification.php:

```        
if (! method_exists($notifiable, 'notify')) {
        throw new SchedulingFailedException(sprintf('%s is not notifiable', get_class($notifiable)));
}
```

if fact, looking at Traits/SnoozeNotifiable.php I see that only the `notifyAt` method is declared, but not `notify`.

The error disappear if I declare the Model as

```class User extends Model {
    use Notifiable, SnoozeNotifiable;

    // ...
}
```

Anyway I would like to know if there's a mistake somewhere in my code, or "simply" something to add in the README.

version "1.0.5"
Laravel "v6.20.27"

**Comment by atymic** [comment]
Good catch, docs updated :)
