### ISSUE TITLE
No scheduled notifications need to be sent

### ISSUE THREAD

**Issue by sunguski07** [thomasjohnkane/snooze#77]
I have done all the configuration and the notifications are being stored in the scheduled notifications table but when I run the "php artisan snooze:send" command it says no scheduled notifications need to be sent.

**Comment by eduduardo** [comment]
This command will only output notifications if some item on `scheduled_notifications.send_at` has a datetime before or equals `now()`. 

Also you need to check your `SCHEDULED_NOTIFICATION_SEND_TOLERANCE`, present in `config/snooze.php` the default is 24 hours before.

**Comment by eduduardo** [comment]
I guess this issue can be closed.

**Comment by atymic** [comment]
Thanks @eduduardo
