### ISSUE TITLE
Sending notifications on one server

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [thomasjohnkane/snooze#78]
Should't we have `->onOneServer()` option set on the scheduler?

https://laravel.com/docs/8.x/scheduling#running-tasks-on-one-server

**Comment by OrkhanAlikhanov** [comment]
@atymic @thomasjohnkane what do you think?

**Comment by atymic** [comment]
Feel free to PR a config option to set this.

**Comment by atymic** [comment]
Closed by #86
