### ISSUE TITLE
Notifications Event : NotificationSent should fire after commits

### ISSUE THREAD

**Issue by arhen** [thomasjohnkane/snooze#80]
I have a case when I've created a listener when notification is sent on laravel that have a simple task which is check if current scheduled notification is sent. I know it's weird because it's actually/already sent but I've check it again on that events.
But from the case, I know that method $notification->isSent() is always false.

I've looked at the code and found [this line ](https://github.com/thomasjohnkane/snooze/blob/master/src/Models/ScheduledNotification.php#L77) from [this closed issue](https://github.com/thomasjohnkane/snooze/issues/14).

From that logic then I know that the result will always false because 
` event(new NotificationSent($this));`  
is firing before 
```
$this->sent_at = Carbon::now();
$this->save();
```
I think it will be good to put it after update event so method like `isSent()` still return true in notificationsSent listener.

**Comment by atymic** [comment]
Feel free to make a PR :)

**Comment by arhen** [comment]
> Feel free to make a PR :)

Finally, you commented out. Sure I will submit my Pr for this. Thank you for reply
