### ISSUE TITLE
[BUG] QueryException: Incorrect table name while running migrate command

### ISSUE THREAD

**Issue by sayandeep-volition** [thomasjohnkane/snooze#82]
After installing the package when I was going to run `php artisan migrate` .
It shows me
Illuminate\Database\QueryException
` SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `target_id` varchar(255) null, `target_type` varchar(255) not null, `target` text not null, `notification_type` varchar(255) not null, `notification` text not null, `send_at` datetime not null, `sent_at` datetime null, `rescheduled_at` datetime null, `cancelled_at` datetime null, `created_at` timestamp null, `updated_at` 
timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`

I have published the config file.
Versions: 
Laravel Framework 7.30.4
PHP 7.4.15

**Comment by adgower** [comment]
I am getting the same problem
laravel 8
php 7.4

**Comment by adgower** [comment]
> After installing the package when I was going to run `php artisan migrate` .
> It shows me
> Illuminate\Database\QueryException
> `` SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` ( ``id`int unsigned not null auto_increment primary key,`target_id`varchar(255) null,`target_type`varchar(255) not null,`target`text not null,`notification_type`varchar(255) not null,`notification`text not null,`send_at`datetime not null,`sent_at`datetime null,`rescheduled_at`datetime null,`cancelled_at`datetime null,`created_at`timestamp null,`updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')`
> 
> I have published the config file.
> Versions:
> Laravel Framework 7.30.4
> PHP 7.4.15

@sayandeep-volition try checking your permissions
This fixed it.
when I ran this: sudo chown -R $USER:www-data storage && sudo chown -R $USER:www-data bootstrap/cache && chmod -R 775 storage && chmod -R 775 bootstrap/cache

**Comment by sayandeep-volition** [comment]
@adgower I'm using Windows env. And permissions are okay. 
Still searching for a solution.

**Comment by modavidc** [comment]
I'm using Laravel 6, in my case this worked: 

`php artisan vendor:publish --provider="Thomasjohnkane\Snooze\ServiceProvider" --tag="config"`

and after execute migrations: 

`php artisan migrate`
