### ISSUE TITLE
findByMeta with target

### ISSUE THREAD

**Issue by abcmoritz** [thomasjohnkane/snooze#96]
Hello,
great package!
But is it possible to get the scheduled_notification by the meta tag but also eager load the target?

Use case:
I have tasks
The task has reminder notifications
The target is the selected user of the task notification
The task is stored in the meta data
I get all reminders / notificaitons for a task with findByMeta as a task attribute

Now a solution could be iterating with a foreach through every notification of the getRemindersAttribute function.
But is it build in and i couldnt figure it out?

**Comment by atymic** [comment]
Not sure exactly what you mean. Could you add a code sample?
Feel free to PR
